apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gw302i66u-go
  janus-idp.io/tekton: gw302i66u-go
  backstage.io/kubernetes-id: gw302i66u-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gw302i66u-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
